//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS1PersonBlackJack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS1PersonBlackJack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _2OfClubs {
            get {
                object obj = ResourceManager.GetObject("2OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("2OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2OfHearts {
            get {
                object obj = ResourceManager.GetObject("2OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2OfSpades {
            get {
                object obj = ResourceManager.GetObject("2OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3OfClubs {
            get {
                object obj = ResourceManager.GetObject("3OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("3OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3OfHearts {
            get {
                object obj = ResourceManager.GetObject("3OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3OfSpades {
            get {
                object obj = ResourceManager.GetObject("3OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4OfClubs {
            get {
                object obj = ResourceManager.GetObject("4OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("4OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4OfHearts {
            get {
                object obj = ResourceManager.GetObject("4OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4OfSpades {
            get {
                object obj = ResourceManager.GetObject("4OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5OfClubs {
            get {
                object obj = ResourceManager.GetObject("5OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("5OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5OfHearts {
            get {
                object obj = ResourceManager.GetObject("5OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5OfSpades {
            get {
                object obj = ResourceManager.GetObject("5OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6OfClubs {
            get {
                object obj = ResourceManager.GetObject("6OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("6OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6OfHearts {
            get {
                object obj = ResourceManager.GetObject("6OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6OfSpades {
            get {
                object obj = ResourceManager.GetObject("6OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7OfClubs {
            get {
                object obj = ResourceManager.GetObject("7OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("7OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7OfHearts {
            get {
                object obj = ResourceManager.GetObject("7OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7OfSpades {
            get {
                object obj = ResourceManager.GetObject("7OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8OfClubs {
            get {
                object obj = ResourceManager.GetObject("8OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("8OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8OfHearts {
            get {
                object obj = ResourceManager.GetObject("8OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8OfSpades {
            get {
                object obj = ResourceManager.GetObject("8OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9OfClubs {
            get {
                object obj = ResourceManager.GetObject("9OfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9OfDiamonds {
            get {
                object obj = ResourceManager.GetObject("9OfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9OfHearts {
            get {
                object obj = ResourceManager.GetObject("9OfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9OfSpades {
            get {
                object obj = ResourceManager.GetObject("9OfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AceOfClubs {
            get {
                object obj = ResourceManager.GetObject("AceOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AceOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("AceOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AceOfHearts {
            get {
                object obj = ResourceManager.GetObject("AceOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AceOfSpades {
            get {
                object obj = ResourceManager.GetObject("AceOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap classic_playing_cards {
            get {
                object obj = ResourceManager.GetObject("classic-playing-cards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackOfClubs {
            get {
                object obj = ResourceManager.GetObject("JackOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("JackOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackOfHearts {
            get {
                object obj = ResourceManager.GetObject("JackOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackOfSpades {
            get {
                object obj = ResourceManager.GetObject("JackOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KingOfClubs {
            get {
                object obj = ResourceManager.GetObject("KingOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KingOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("KingOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KingOfHearts {
            get {
                object obj = ResourceManager.GetObject("KingOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KingOfSpades {
            get {
                object obj = ResourceManager.GetObject("KingOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QueenOfClubs {
            get {
                object obj = ResourceManager.GetObject("QueenOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QueenOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("QueenOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QueenOfHearts {
            get {
                object obj = ResourceManager.GetObject("QueenOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QueenOfSpades {
            get {
                object obj = ResourceManager.GetObject("QueenOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenOfClubs {
            get {
                object obj = ResourceManager.GetObject("TenOfClubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenOfDiamonds {
            get {
                object obj = ResourceManager.GetObject("TenOfDiamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenOfHearts {
            get {
                object obj = ResourceManager.GetObject("TenOfHearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenOfSpades {
            get {
                object obj = ResourceManager.GetObject("TenOfSpades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
